site_name: QARTOD

# Repository
repo_name: ocefpaf/qartod_manuals
repo_url: https://github.com/ocefpaf/qartod_manuals
edit_uri: edit/main/docs/

theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - navigation.indexes
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.action.edit
    - content.action.view
    - content.code.annotate

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

nav:
  - Home: index.md
  - Water Level: Water_Level.md
  - ADCP: ADCP.md
  - pH: pH.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ocefpaf
  version:
    provider: mike

markdown_extensions:
  - abbr
  - toc
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
