[project]
authors = ["Filipe Fernandes <ocefpaf@gmail.com>"]
channels = ["conda-forge"]
description = "Markdown version of the QARTOD manuals"
name = "QARTOD Manuals"
platforms = ["linux-64"]
version = "1.0.0"

[tasks.pdf]
args = ["manual"]
cmd = "pandoc docs/{{ manual }}.md --from=markdown --output=compiled_manuals/{{ manual }}.pdf --to=pdf --pdf-engine=tectonic"

[tasks.docx]
args = ["manual"]
cmd = "pandoc docs/{{ manual }}.md --from=markdown --output=compiled_manuals/{{ manual }}.docx --to=docx"

[tasks.mkdocs]
cmd = "mkdocs build --clean --verbose"

[tasks.serve]
cmd = "mkdocs serve"

[dependencies]
python = "3.13.*"
mike = ">=2.1.3,<3"
mkdocs = ">=1.6.1,<2"
mkdocs-material = ">=9.6.14,<10"
pandoc = ">=3.7.0.2,<4"
tectonic = ">=0.15.0,<0.16"
mkdocs-git-revision-date-localized-plugin = ">=1.2.9,<2"
