name: Build Docx/PDF

on:
  pull_request:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: prefix-dev/setup-pixi@a09b6247153796b190642a2b53fac4241043cf6f # v0.10.0
      - run: >
          for manual in  Water_Level ADCP; do pixi run pdf "${manual}"; done
          && for manual in  Water_Level ADCP; do pixi run docx "${manual}"; done

      - name: Upload artifacts to Github
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: compiled_manuals/

      - name: Upload artifacts to Github release
        if: success() && github.event_name == 'release'
        uses: svenstaro/upload-release-action@29e53e917877a24fad85510ded594ab3c9ca12de # v2.11.5
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: compiled_manuals/*
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
